# Generated by Django 5.2.17 on 2026-09-15 20:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("api", "API 数据"),
                            ("dataset", "历史数据集"),
                            ("simulation", "模拟数据"),
                            ("manual", "人工录入"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license", models.CharField(blank=True, max_length=500)),
                ("attribution", models.TextField(blank=True)),
                ("original_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MapLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                ("image_url", models.CharField(blank=True, max_length=500)),
                ("image_width", models.PositiveIntegerField(default=1000)),
                ("image_height", models.PositiveIntegerField(default=700)),
                ("attribution", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["region", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("unit", models.CharField(max_length=30)),
                (
                    "station_kind",
                    models.CharField(
                        choices=[
                            ("water", "水环境"),
                            ("weather", "气象"),
                            ("air", "空气"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["station_kind", "code"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_demo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("seed", models.PositiveIntegerField(default=20260916)),
                ("version", models.CharField(default="1", max_length=40)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("river", "河流"),
                            ("lake", "湖泊"),
                            ("park", "公园"),
                            ("plant", "植物点"),
                            ("waste", "分类投放点"),
                            ("trail", "绿色步道"),
                            ("campus", "校园地点"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "x_ratio",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "y_ratio",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "未提供"),
                            ("WGS84", "WGS84"),
                            ("GCJ02", "GCJ02"),
                            ("BD09", "BD09"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_note", models.CharField(blank=True, max_length=500)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "map_layout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="ecology.maplayout",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="places",
                        to="ecology.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="maplayout",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maps",
                to="ecology.region",
            ),
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("seed", models.PositiveIntegerField()),
                ("generator_version", models.CharField(default="1", max_length=40)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("counts", models.PositiveIntegerField(default=0)),
                ("elapsed_ms", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulation_runs",
                        to="ecology.datasource",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="ecology.simulationscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("water", "水环境"),
                            ("weather", "气象"),
                            ("air", "空气"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stations",
                        to="ecology.place",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stations",
                        to="ecology.region",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.FloatField(blank=True, null=True)),
                ("observed_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("valid", "有效"),
                            ("missing", "缺失"),
                            ("suspect", "可疑"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=64, unique=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="ecology.metric",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="ecology.datasource",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="ecology.simulationrun",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="ecology.station",
                    ),
                ),
            ],
            options={
                "ordering": ["observed_at", "station__code", "metric__code"],
            },
        ),
        migrations.CreateModel(
            name="WaterBody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_body",
                        to="ecology.place",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="station",
            name="water_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stations",
                to="ecology.waterbody",
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["region", "kind"], name="ecology_pla_region__9068dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="maplayout",
            constraint=models.UniqueConstraint(
                fields=("region", "version"), name="map_region_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["station", "metric", "observed_at"],
                name="obs_station_metric_time",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["source", "observed_at"], name="obs_source_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quality_status", "missing"), ("value__isnull", True)),
                    models.Q(
                        models.Q(("quality_status", "missing"), _negated=True),
                        ("value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="obs_missing_value_consistent",
            ),
        ),
    ]
