# Generated by Django 5.2.17 on 2026-09-17 07:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("ecology", "0001_initial"),
        (
            "recognition",
            "0003_modelversion_artifact_modelversion_config_digest_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=32, unique=True)),
                ("definition", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "评估规则版本",
                "verbose_name_plural": "评估规则版本",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="one_active_assessment_ruleset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "处理中"),
                            ("succeeded", "完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "未提供"),
                            ("WGS84", "WGS84"),
                            ("GCJ02", "GCJ02"),
                            ("BD09", "BD09"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detections", models.JSONField(blank=True, default=list)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=8)),
                ("causes", models.JSONField(blank=True, default=list)),
                ("rule_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recognition.modelversion",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_jobs",
                        to="ecology.station",
                    ),
                ),
                (
                    "water_body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_jobs",
                        to="ecology.waterbody",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="ecology.ruleset",
                    ),
                ),
            ],
            options={
                "verbose_name": "河道评估任务",
                "verbose_name_plural": "河道评估任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
