# Generated by Django 5.2.17 on 2026-09-20 18:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationrun",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("maintain_simulation", "可以预览和执行模拟批次保留策略")
                ],
            },
        ),
        migrations.CreateModel(
            name="SimulationCleanupPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("policy", models.JSONField(default=dict)),
                ("candidate_ids", models.JSONField(default=list)),
                ("observation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟批次清理预览",
                "verbose_name_plural": "模拟批次清理预览",
            },
        ),
        migrations.CreateModel(
            name="SimulationRetentionPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "retain_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                (
                    "keep_successful",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "模拟批次保留策略",
                "verbose_name_plural": "模拟批次保留策略",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("id", 1),
                            ("keep_successful__gte", 1),
                            ("keep_successful__lte", 100),
                            ("retain_days__gte", 30),
                            ("retain_days__lte", 3650),
                        ),
                        name="simulation_policy_limits",
                    )
                ],
            },
        ),
    ]
