# Generated by Django 5.2.17 on 2026-09-20 00:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("ecology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("source", models.URLField(blank=True)),
                ("license", models.CharField(blank=True, max_length=100)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("artifact", models.CharField(blank=True, max_length=500)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("preprocessing", models.JSONField(blank=True, default=dict)),
                ("threshold", models.FloatField(default=0.4)),
                ("scope", models.TextField(blank=True)),
                ("evaluation", models.JSONField(blank=True, default=dict)),
                ("config_digest", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "河道检测模型版本",
                "verbose_name_plural": "河道检测模型版本",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"),
                        name="unique_detection_model_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("threshold__gte", 0), ("threshold__lte", 1)
                        ),
                        name="detection_threshold_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("enabled", True)),
                        fields=("enabled",),
                        name="one_enabled_detection_model",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=32, unique=True)),
                ("definition", models.JSONField()),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "图像教学规则版本",
                "verbose_name_plural": "图像教学规则版本",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="one_active_image_ruleset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssessmentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_snapshot", models.JSONField(blank=True, default=dict)),
                ("rule_snapshot", models.JSONField(blank=True, default=dict)),
                ("rule_version", models.CharField(blank=True, max_length=32)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True,
                        choices=[("WGS84", "WGS84"), ("GCJ02", "GCJ02")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("detections", models.JSONField(blank=True, default=list)),
                ("image_width", models.PositiveIntegerField(blank=True, null=True)),
                ("image_height", models.PositiveIntegerField(blank=True, null=True)),
                ("issues", models.JSONField(blank=True, default=dict)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("causes", models.JSONField(blank=True, default=list)),
                ("decision", models.CharField(blank=True, max_length=20)),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_jobs",
                        to="assets.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_jobs",
                        to="ecology.station",
                    ),
                ),
                (
                    "water_body",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_jobs",
                        to="ecology.waterbody",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assessments.detectionmodel",
                    ),
                ),
                (
                    "rule_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="assessments.ruleset",
                    ),
                ),
            ],
            options={
                "verbose_name": "河道图像评估任务",
                "verbose_name_plural": "河道图像评估任务",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("asset__isnull", False)),
                        fields=("owner", "asset"),
                        name="one_assessment_per_owner_asset",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("score__isnull", True),
                            models.Q(("score__gte", 0), ("score__lte", 100)),
                            _connector="OR",
                        ),
                        name="image_rule_score_range",
                    ),
                ],
            },
        ),
    ]
