# Generated by Django 5.2.17 on 2026-09-15 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecology", "0001_initial"),
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("resolved", "已处理")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.content",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.place",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("content__isnull", True), ("place__isnull", False)
                            ),
                            models.Q(
                                ("content__isnull", False), ("place__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="favorite_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("place__isnull", False)),
                        fields=("owner", "place"),
                        name="favorite_unique_place",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("content__isnull", False)),
                        fields=("owner", "content"),
                        name="favorite_unique_content",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge.content",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.place",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("content__isnull", True), ("place__isnull", False)
                            ),
                            models.Q(
                                ("content__isnull", False), ("place__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="history_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("place__isnull", False)),
                        fields=("owner", "place"),
                        name="history_unique_place",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("content__isnull", False)),
                        fields=("owner", "content"),
                        name="history_unique_content",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visited_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecology.place"
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "place", "visited_on"),
                        name="one_self_visit_per_day",
                    )
                ],
            },
        ),
    ]
