# Generated by Django 5.2.17 on 2026-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementStats",
            fields=[],
            options={
                "verbose_name": "管理统计与查询",
                "verbose_name_plural": "管理统计与查询",
                "proxy": True,
                "default_permissions": ("view",),
                "indexes": [],
                "constraints": [],
            },
            bases=("common.auditlog",),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changed_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="model_label",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
