# Generated by Django 5.2.17 on 2026-09-20 14:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        (
            "recognition",
            "0003_modelversion_artifact_modelversion_config_digest_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="允许外部 AI 解读"),
                ),
                (
                    "daily_turn_limit",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="每用户每日成功回合上限",
                    ),
                ),
                (
                    "per_user_attempt_limit",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="每用户每日提交上限",
                    ),
                ),
                (
                    "global_daily_attempt_limit",
                    models.PositiveIntegerField(
                        default=200,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="全站每日提交上限",
                    ),
                ),
                (
                    "global_daily_token_limit",
                    models.PositiveIntegerField(
                        default=1000000,
                        validators=[
                            django.core.validators.MinValueValidator(1024),
                            django.core.validators.MaxValueValidator(100000000),
                        ],
                        verbose_name="全站每日 token 预算",
                    ),
                ),
                (
                    "max_output_tokens",
                    models.PositiveIntegerField(
                        default=600,
                        validators=[
                            django.core.validators.MinValueValidator(64),
                            django.core.validators.MaxValueValidator(2048),
                        ],
                        verbose_name="单次最大输出 token",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=45,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="单次硬超时秒数",
                    ),
                ),
                (
                    "queue_limit",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="全站待处理任务上限",
                    ),
                ),
                (
                    "max_concurrency",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="全站并发上限",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "网关配置",
                "verbose_name_plural": "网关配置",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="llm_single_config"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recognition", "花卉解读"),
                            ("assessment", "河道解读"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("context_summary", models.TextField()),
                ("consent_version", models.CharField(max_length=32)),
                ("include_image", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "assessment_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_sessions",
                        to="assessments.assessmentjob",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recognition_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_sessions",
                        to="recognition.recognitionjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "私人 AI 会话",
                "verbose_name_plural": "私人 AI 会话",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UsageLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("day", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("reserved_tokens", models.PositiveIntegerField()),
                ("accounted_tokens", models.PositiveIntegerField(default=0)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("usage_estimated", models.BooleanField(default=False)),
                ("dispatched", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("used_image", models.BooleanField(default=False)),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("timeout_seconds", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_entries",
                        to="llm.llmsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 用量账目（不含对话内容）",
                "verbose_name_plural": "AI 用量账目（不含对话内容）",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LLMTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=200)),
                ("used_image", models.BooleanField(default=False)),
                ("model", models.CharField(default="deepseek-flash", max_length=32)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="llm.llmsession",
                    ),
                ),
                (
                    "ledger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turn",
                        to="llm.usageledger",
                    ),
                ),
            ],
            options={
                "verbose_name": "私人 AI 回合",
                "verbose_name_plural": "私人 AI 回合",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="llmsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("kind", "recognition"),
                        ("recognition_job__isnull", False),
                    ),
                    models.Q(
                        ("assessment_job__isnull", False),
                        ("kind", "assessment"),
                        ("recognition_job__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="llm_one_source",
            ),
        ),
        migrations.AddIndex(
            model_name="usageledger",
            index=models.Index(
                fields=["owner", "day", "status"], name="llm_owner_day_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageledger",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="llm_user_request_unique"
            ),
        ),
    ]
