# Generated by Django 5.2.17 on 2026-09-20 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("ecology", "0001_initial"),
        ("knowledge", "0001_initial"),
        ("llm", "0001_initial"),
        (
            "recognition",
            "0003_modelversion_artifact_modelversion_config_digest_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="llmsession",
            name="llm_one_source",
        ),
        migrations.RemoveIndex(
            model_name="usageledger",
            name="llm_owner_day_status",
        ),
        migrations.AddField(
            model_name="llmsession",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_sessions",
                to="knowledge.content",
            ),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_sessions",
                to="ecology.place",
            ),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_sessions",
                to="ecology.region",
            ),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_sessions",
                to="knowledge.route",
            ),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="scope",
            field=models.CharField(
                choices=[
                    ("recognition", "AI 识别"),
                    ("explore", "生态导览"),
                    ("learn", "科普智游"),
                ],
                db_index=True,
                default="recognition",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="llmsession",
            name="water_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_sessions",
                to="ecology.waterbody",
            ),
        ),
        migrations.AddField(
            model_name="llmturn",
            name="context_revision",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="usageledger",
            name="scope",
            field=models.CharField(
                choices=[
                    ("recognition", "AI 识别"),
                    ("explore", "生态导览"),
                    ("learn", "科普智游"),
                ],
                db_index=True,
                default="recognition",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="daily_turn_limit",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="每用户每板块每日成功回合上限",
            ),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="per_user_attempt_limit",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="每用户每板块每日提交上限",
            ),
        ),
        migrations.AlterField(
            model_name="llmsession",
            name="consent_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="llmsession",
            name="kind",
            field=models.CharField(
                choices=[
                    ("recognition", "花卉解读"),
                    ("assessment", "河道解读"),
                    ("explore", "生态导览"),
                    ("learn", "科普智游"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="usageledger",
            index=models.Index(
                fields=["owner", "scope", "day", "status"],
                name="llm_owner_scope_day_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "recognition"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", False),
                        ("region__isnull", True),
                        ("route__isnull", True),
                        ("scope", "recognition"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", False),
                        ("content__isnull", True),
                        ("kind", "assessment"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", True),
                        ("route__isnull", True),
                        ("scope", "recognition"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "explore"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", False),
                        ("route__isnull", True),
                        ("scope", "explore"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "learn"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", False),
                        ("route__isnull", True),
                        ("scope", "learn"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "explore"),
                        ("place__isnull", False),
                        ("recognition_job__isnull", True),
                        ("region__isnull", True),
                        ("route__isnull", True),
                        ("scope", "explore"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "explore"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", True),
                        ("route__isnull", True),
                        ("scope", "explore"),
                        ("water_body__isnull", False),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", False),
                        ("kind", "learn"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", True),
                        ("route__isnull", True),
                        ("scope", "learn"),
                        ("water_body__isnull", True),
                    ),
                    models.Q(
                        ("assessment_job__isnull", True),
                        ("content__isnull", True),
                        ("kind", "learn"),
                        ("place__isnull", True),
                        ("recognition_job__isnull", True),
                        ("region__isnull", True),
                        ("route__isnull", False),
                        ("scope", "learn"),
                        ("water_body__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="llm_scoped_source",
            ),
        ),
    ]
