# Generated by Django 5.2.17 on 2026-09-15 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("source", models.URLField(blank=True)),
                ("license", models.CharField(blank=True, max_length=100)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("preprocessing", models.JSONField(blank=True, default=dict)),
                ("threshold", models.FloatField(default=0.8)),
            ],
            options={
                "verbose_name": "模型版本",
                "verbose_name_plural": "模型版本",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_model_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("threshold__gte", 0), ("threshold__lte", 1)
                        ),
                        name="model_threshold_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecognitionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("message", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assets.asset",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recognition.modelversion",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "识别任务",
                "verbose_name_plural": "识别任务",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("asset__isnull", False)),
                        fields=("owner", "asset"),
                        name="one_job_per_owner_asset",
                    )
                ],
            },
        ),
    ]
