# Generated by Django 5.2.17 on 2026-09-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueControl",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="recognition",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
