# Generated by Django 5.2.17 on 2026-09-16 06:41

from django.db import migrations, models


def disable_unverified_m1_models(apps, schema_editor):
    # M1 metadata alone never constituted a verified runtime artifact.
    apps.get_model('recognition', 'ModelVersion').objects.update(enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_queuecontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="artifact",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="config_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="evaluation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="scope",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="recognitionjob",
            name="model_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(disable_unverified_m1_models, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enabled", True)),
                fields=("enabled",),
                name="one_enabled_recognition_model",
            ),
        ),
    ]
