# Generated by Django 5.2.17 on 2026-09-20 18:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherGate",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("block_reason", models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                        verbose_name="WGS84 纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                        verbose_name="WGS84 经度",
                    ),
                ),
                (
                    "scope_note",
                    models.CharField(
                        default="附近约 1 公里网格的气象资料，不代表校园内实测。",
                        max_length=400,
                        verbose_name="范围说明",
                    ),
                ),
                (
                    "coordinate_source",
                    models.CharField(max_length=500, verbose_name="坐标核对来源"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="公开可查询"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "天气查询地点",
                "verbose_name_plural": "天气查询地点",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeatherMonth",
            fields=[
                (
                    "month",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "天气月度请求账本",
                "verbose_name_plural": "天气月度请求账本",
                "ordering": ["-month"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reserved__lte", 30000)),
                        name="weather_month_hard_limit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weather", "当前天气"),
                            ("air", "当前空气质量"),
                            ("alerts", "当前天气预警"),
                        ],
                        max_length=10,
                    ),
                ),
                ("point", models.CharField(max_length=30)),
                ("reserved_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(default="reserved", max_length=30)),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weatherdata.weatherlocation",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="weatherdata.weathermonth",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气上游请求记录",
                "verbose_name_plural": "天气上游请求记录",
                "ordering": ["-reserved_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weather", "当前天气"),
                            ("air", "当前空气质量"),
                            ("alerts", "当前天气预警"),
                        ],
                        max_length=10,
                    ),
                ),
                ("point", models.CharField(max_length=30)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("retry_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("last_reason", models.CharField(blank=True, max_length=40)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="weatherdata.weatherlocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "天气持久缓存",
                "verbose_name_plural": "天气持久缓存",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "kind", "point"),
                        name="weather_cache_unique_point",
                    )
                ],
            },
        ),
    ]
